travis:
  secure:
    BINSTAR_TOKEN: KBeRf78LdwKal7Qgq57riJFwo/tj38ajg+//Ow4y+VycDas4ffU3eLtNM6vUL4t60s5i/dRbKVo964gGoLHDXHC8VQkIuyJUBsU7Ed1b9BBV6Xws3HHmzfKEetIQKa9groIYF+eEQU1tJkKBNWY4Bgf9F6n25QBG1BCPrupyysbp10NMcvBuqt8NCAmOXrKnVjM3SAUsgQXz/OMlRBdjPbznAeBWlF8IH0Vm23wBwKm0xXaCWs+klmH6R7C4iJ768jI5gNyD1k/2w2e3fVbQJQSJSXOkxMJ5NFPI4QQ3YfXYgWhnYON08vqsaPZMenw0W2G3u2eKe1pGAtWO0rPjAmLKxVFx+2NXldXuOXCShJPdO8keORXRtHHv/55Fjz/BOMFg+Fgu9DSatqrGylseIoTTsxcdAdMo9+/NQk5h6ODq8rXsskFZS6qQIuQBpA2Eb9OZOoq+cBma+yCzFAxWUc8Ff27CjvHdARdkqyF7RNOKAc3I+Jbm83Oca8/E9wfyU52zl2Rxy/M5XbgdN3aon0Z4D1EJPT2G8YswYzcL+9yMdLXNp5pIm6wxVJGrTMKYxytCdpbCeRyBqgBnbAqB0eSp62JtelAS4hTjrw9eztYDcmvmW8yKvdhy0d/+1xrtaKtHN+9cewz0DWoqBEK7yMjnrnTIWwBH3IjR3wUB8co=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
