appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: f/AB30tvW2+FYNfqgI1spM3JYF2Mtx9mOdileV3e4WbfFRKEdmhnm6hnYzUdT48dRJG7Fx6TUczZwDoLKJXBgS/5SYL1yYsuyXbufiI/XIh0Jwl5QLcMH8HKNRSuP5dNbDhwPVh1dfs96bN6pgIYc06Lm5r9yIuxYVviGhV+T8IUOzqtdWmbLFIb8vxg6co4cIIcad5l1hsxtvCGEPj6lcQ14gcsyvdBo97U7E7CEquYod+EUE8rGYKh3jT1L9eeQEGRuR7cvZVTARHMf10dOwQ4Rmv8f4ho8/rwhahVNGE2ac2mBvvfhbXaoAPOl6873QI1IEWu3xYMglw3q4hfkjdbnnc6tq9ff1FtQk1WPPauI4IA/3Bd5cXGpHxNkU2f23yRa8LD5ZepkFbERoiK3z/oYWOVxVZuQVy1aKQi7uAYWrToE8hDElRN6h8zl824MEL8gBX5g1r1wH20i8kYfhbZDOzl9gVB9GG5eb23AoNa2lisAg5JEEa3pac+6q3c5p5rZulZajwdlXCGszB/8jM8DaHVGRa6PbkA9v6wHXkeSRKEy7B1jNSBGhRpAsY5/x4KLJa6vwrA3lbhJ5ZyDy9OKrZfRfPNLcoVeYjeV5anzA1dxxfCki6W7O8Ths8gsvZgeYzbbzc1MlJ0ENjpyrs6rcyTyQhmK0qThsF26mU=}
